
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 616420
	#The name of the modpack
	modpackName = "DarkRPG Forge Edition"
	#The version of the modpack
	modpackVersion = "2.1.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

